package refyne

import (
	"fmt"
	"go/format"
	"io"
	"reflect"
	"sort"
	"strings"

	"github.com/fyne-io/refyne/internal/guidefs"
	"github.com/fyne-io/refyne/internal/tools"

	"fyne.io/fyne/v2"
)

// ExportGo generates a full Go package for the given object and writes it to the provided file handle
func ExportGo(obj fyne.CanvasObject, d Context, name string, w io.Writer) error {
	guidefs.InitOnce()

	packagesList := packagesRequired(obj, d)

	// Really this needs to be a full dependency analysis but for now a simple sort of widgets before containers may work
	varListWidgets, varListContainers := varsRequired(obj, d)
	sort.Strings(varListWidgets)
	sort.Strings(varListContainers)

	code := exportCode(packagesList, append(varListWidgets, varListContainers...), obj, d, name)

	_, err := w.Write([]byte(code))
	return err
}

// ExportGoPreview generates a preview version of the Go code with a `main()` method for the given object and writes it to the file handle
func ExportGoPreview(obj fyne.CanvasObject, d Context, w io.Writer) error {
	guidefs.InitOnce()

	packagesList := packagesRequired(obj, d)
	packagesList = append(packagesList, "app")

	// Really this needs to be a full dependency analysis but for now a simple sort of widgets before containers may work
	varListWidgets, varListContainers := varsRequired(obj, d)
	sort.Strings(varListWidgets)
	sort.Strings(varListContainers)

	code := exportCode(packagesList, append(varListWidgets, varListContainers...), obj, d, "main")

	code += `
func main() {
	a := app.New()
	w := a.NewWindow("Hello")
	gui := newGUI()
	gui.win = w
	w.SetContent(gui.makeUI())
	w.ShowAndRun()
}
`
	_, err := w.Write([]byte(code))

	return err
}

func exportCode(pkgs, vars []string, obj fyne.CanvasObject, d Context, name string) string {
	for i := 0; i < len(pkgs); i++ {
		if pkgs[i] == "xWidget" {
			pkgs[i] = `xWidget	"fyne.io/x/fyne/widget"`

			continue
		}

		if pkgs[i] != "fmt" && !strings.Contains(pkgs[i], "/") {
			pkgs[i] = "fyne.io/fyne/v2/" + pkgs[i]
		}

		pkgs[i] = fmt.Sprintf(`	"%s"`, pkgs[i])
	}

	battrs := make(map[fyne.CanvasObject][]string)
	for obj, attrs := range d.Attrs() {
		battrs[obj] = attrs
	}

	genids := make(map[string]bool)
	for obj, props := range d.Metadata() {
		if props["name"] != "" {
			continue
		}
		props["name"] = fmt.Sprintf("%p", obj)[1:]
		props["name-is-generated"] = "1"

		genids[props["name"]] = true

		d.Metadata()[obj] = props
	}

	defs := make(map[string]string)

	_, clazz := getTypeOf(obj)
	main := guidefs.GoString(clazz, obj, d, defs)
	setup := ""

	for name := range genids {
		setup += name + " := " + defs[name] + "\n"
	}

	for _, key := range vars {
		name := strings.Split(key, " ")[0]
		if genids[name] {
			continue
		}
		setup += "g." + name + " = " + defs[name] + "\n"
	}

	attrs := []string{}
	for obj, props := range d.Metadata() {
		id := "g." + props["name"]
		if genids[props["name"]] {
			id = props["name"]
		}

		for _, attr := range d.Attrs()[obj] {
			attrs = append(attrs, id+"."+attr)
		}
	}

	for obj, attrs := range battrs {
		d.Attrs()[obj] = attrs
	}

	for obj, props := range d.Metadata() {
		if props["name-is-generated"] != "1" {
			continue
		}
		delete(props, "name-is-generated")
		delete(props, "name")

		d.Metadata()[obj] = props
	}

	guiName := "gui"
	guiNameUpper := ""
	layoutHelper := ""
	if name != "main" {
		guiName = name + "Gui"
		guiNameUpper = strings.ToUpper(string([]byte{name[0]})) + name[1:]
	} else {
		layoutHelper = `type wrappedLayout struct {
	layout  func([]fyne.CanvasObject, fyne.Size)
	minSize func([]fyne.CanvasObject) fyne.Size
}

func (w wrappedLayout) Layout(objs []fyne.CanvasObject, s fyne.Size) {
	w.layout(objs, s)
}

func (w wrappedLayout) MinSize(objs []fyne.CanvasObject) fyne.Size {
	return w.minSize(objs)
}

func wrapLayout(l func([]fyne.CanvasObject, fyne.Size), m func([]fyne.CanvasObject) fyne.Size) fyne.Layout {
	return wrappedLayout{layout: l, minSize: m}
}`
	}

	data := struct {
		Pkgs         []string
		LayoutHelper string
		GuiName      string
		GuiNameUpper string
		Vars         []string
		Attrs        []string
		Setup        string
		Main         string
	}{
		Pkgs:         pkgs,
		LayoutHelper: layoutHelper,
		GuiName:      guiName,
		GuiNameUpper: guiNameUpper,
		Vars:         vars,
		Attrs:        attrs,
		Setup:        setup,
		Main:         main,
	}
	code, err := tools.RenderCode(`// auto-generated
// Code generated by GUI builder.

package main

import (
	"fyne.io/fyne/v2"
{{- range .Pkgs }}
	{{.}}
{{- end }}
)

{{.LayoutHelper}}

type {{.GuiName}} struct {
	win fyne.Window

{{ range .Vars }}
	{{.}}
{{- end }}
}

func new{{.GuiNameUpper}}GUI() *{{.GuiName}} {
	return &{{.GuiName}}{}
}

func (g *{{.GuiName}}) makeUI() fyne.CanvasObject {
	{{.Setup}}

	{{- range .Attrs}}
		{{.}}
	{{- end}}

	return {{.Main}}
}`, data)
	if err != nil {
		fyne.LogError("Failed to generate GUI code", err)
		return code
	}

	formatted, err := format.Source([]byte(code))
	if err != nil {
		fyne.LogError("Failed to format GUI code", err)
		return code
	}
	return string(formatted)
}

func packagesRequired(obj fyne.CanvasObject, d Context) []string {
	ret := []string{"container"}
	var objs []fyne.CanvasObject
	if c, ok := obj.(*fyne.Container); ok {
		objs = c.Objects
		layout, ok := d.Metadata()[c]["layout"]
		if ok && (layout == "Form" || layout == "CustomPadded" || layout == "GridWrap") {
			ret = append(ret, "layout")
		}
	} else {
		class := reflect.TypeOf(obj).String()
		info := guidefs.Lookup(class)

		if info != nil && info.IsContainer() {
			ret = packagesRequiredForWidget(obj, d)
			objs = info.Children(obj)
		} else {
			return packagesRequiredForWidget(obj, d)
		}
	}

	for _, w := range objs {
		for _, p := range packagesRequired(w, d) {
			added := false
			for _, exists := range ret {
				if p == exists {
					added = true
					break
				}
			}
			if !added {
				ret = append(ret, p)
			}
		}
	}
	return ret
}

func packagesRequiredForWidget(w fyne.CanvasObject, d Context) []string {
	_, name := getTypeOf(w)
	if pkgs := guidefs.Lookup(name).Packages; pkgs != nil {
		return pkgs(w, d)
	}

	if _, ok := w.(fyne.Widget); ok {
		return []string{"widget"}
	}

	return []string{}
}

func varsRequired(obj fyne.CanvasObject, d Context) (widgets, containers []string) {
	name := d.Metadata()[obj]["name"]

	if c, ok := obj.(*fyne.Container); ok {
		if name != "" {
			containers = append(containers, name+" *fyne.Container")
		}

		for _, w := range c.Objects {
			w2, c2 := varsRequired(w, d)
			if len(w2) > 0 {
				widgets = append(widgets, w2...)
			}
			if len(c2) > 0 {
				containers = append(containers, c2...)
			}
		}
	} else {
		class := reflect.TypeOf(obj).String()
		info := guidefs.Lookup(class)

		if info != nil && info.IsContainer() {
			for _, child := range info.Children(obj) {
				w2, c2 := varsRequired(child, d)

				if len(w2) > 0 {
					widgets = append(widgets, w2...)
				}
				if len(c2) > 0 {
					containers = append(containers, c2...)
				}
			}
		}

		if name != "" {
			_, class := getTypeOf(obj)
			widgets = append(widgets, name+" "+class)
		}
	}

	return
}
