package refyne

import (
	"bytes"
	"fmt"
	"sort"
	"testing"

	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"

	"github.com/fyne-io/refyne/internal/tools"
	"github.com/stretchr/testify/assert"
)

func TestExportGo(t *testing.T) {
	ctx := DefaultContext()

	list := &widget.List{}
	ctx.Metadata()[list] = make(map[string]string)
	ctx.Metadata()[list]["name"] = "lili"

	btn := &widget.Button{}
	ctx.Metadata()[btn] = make(map[string]string)
	ctx.Metadata()[btn]["name"] = "bubu"

	obj := container.NewVBox(list, btn)
	ctx.Metadata()[obj] = make(map[string]string)
	ctx.Metadata()[obj]["name"] = "coco"

	name := "what"
	buf := &bytes.Buffer{}
	assert.NoError(t, ExportGo(obj, ctx, name, buf))

	exp := `// auto-generated
// Code generated by GUI builder.

package main

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

type whatGui struct {
	win fyne.Window

	bubu *widget.Button
	lili *widget.List
	coco *fyne.Container
}

func newWhatGUI() *whatGui {
	return &whatGui{}
}

func (g *whatGui) makeUI() fyne.CanvasObject {
	g.bubu = widget.NewButton("", nil)
	g.lili = widget.NewList(func() int {
		return 5
	}, func() fyne.CanvasObject {
		return widget.NewLabel("Template Object")
	}, func(id widget.ListItemID, item fyne.CanvasObject) {
		item.(*widget.Label).SetText(fmt.Sprintf("Item %d", id+1))
	})
	g.coco = container.NewVBox(
		g.lili,
		g.bubu)

	return g.coco
}
`

	assert.Equal(t, exp, buf.String())
}

func TestExportGoButton(t *testing.T) {
	ctx := DefaultContext()

	btn := widget.NewButton("Foo", nil)
	ctx.Metadata()[btn] = make(map[string]string)
	ctx.Metadata()[btn]["name"] = "bubu"
	ctx.Metadata()[btn]["OnTapped"] = "g.coco.Hide"

	obj := container.NewVBox(btn)
	ctx.Metadata()[obj] = make(map[string]string)
	ctx.Metadata()[obj]["name"] = "coco"

	name := "what"
	buf := &bytes.Buffer{}
	assert.NoError(t, ExportGo(obj, ctx, name, buf))

	exp := `// auto-generated
// Code generated by GUI builder.

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

type whatGui struct {
	win fyne.Window

	bubu *widget.Button
	coco *fyne.Container
}

func newWhatGUI() *whatGui {
	return &whatGui{}
}

func (g *whatGui) makeUI() fyne.CanvasObject {
	g.bubu = widget.NewButton("Foo", nil)
	g.coco = container.NewVBox(
		g.bubu)

	g.bubu.OnTapped = g.coco.Hide

	return g.coco
}
`

	assert.Equal(t, exp, buf.String())
}

func TestExportGoEntry(t *testing.T) {
	ctx := DefaultContext()

	btn := widget.NewEntry()
	ctx.Metadata()[btn] = make(map[string]string)
	ctx.Metadata()[btn]["name"] = "enen"
	ctx.Metadata()[btn]["OnSubmitted"] = "g.coco.Hide"

	obj := container.NewVBox(btn)
	ctx.Metadata()[obj] = make(map[string]string)
	ctx.Metadata()[obj]["name"] = "coco"

	name := "what"
	buf := &bytes.Buffer{}
	assert.NoError(t, ExportGo(obj, ctx, name, buf))

	exp := `// auto-generated
// Code generated by GUI builder.

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

type whatGui struct {
	win fyne.Window

	enen *widget.Entry
	coco *fyne.Container
}

func newWhatGUI() *whatGui {
	return &whatGui{}
}

func (g *whatGui) makeUI() fyne.CanvasObject {
	g.enen = widget.NewEntry()
	g.coco = container.NewVBox(
		g.enen)

	g.enen.OnSubmitted = g.coco.Hide

	return g.coco
}
`

	assert.Equal(t, exp, buf.String())
}

func TestExportGoWithoutId(t *testing.T) {
	ctx := DefaultContext()

	ntr := widget.NewEntry()
	ctx.Metadata()[ntr] = make(map[string]string)
	ctx.Metadata()[ntr]["OnSubmitted"] = "g.coco.Hide"

	id := fmt.Sprintf("%p", ntr)[1:]

	obj := container.NewVBox(ntr)
	ctx.Metadata()[obj] = make(map[string]string)
	ctx.Metadata()[obj]["name"] = "coco"

	name := "what"
	buf := &bytes.Buffer{}
	assert.NoError(t, ExportGo(obj, ctx, name, buf))

	exp, err := tools.RenderCode(`// auto-generated
// Code generated by GUI builder.

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

type whatGui struct {
	win fyne.Window

	coco *fyne.Container
}

func newWhatGUI() *whatGui {
	return &whatGui{}
}

func (g *whatGui) makeUI() fyne.CanvasObject {
	{{.}} := widget.NewEntry()
	g.coco = container.NewVBox(
		{{.}})

	{{.}}.OnSubmitted = g.coco.Hide

	return g.coco
}
`, id)
	assert.NoError(t, err)

	assert.Equal(t, exp, buf.String())
}

func TestExportGoWithoutIds(t *testing.T) {
	ctx := DefaultContext()

	ntr := widget.NewEntry()
	ctx.Metadata()[ntr] = make(map[string]string)
	ctx.Metadata()[ntr]["OnSubmitted"] = "g.coco.Hide"
	ntrid := fmt.Sprintf("%p", ntr)[1:]

	btn := widget.NewButton("Foo", nil)
	ctx.Metadata()[btn] = make(map[string]string)
	ctx.Metadata()[btn]["OnTapped"] = ntrid + ".Hide"
	btnid := fmt.Sprintf("%p", btn)[1:]

	box := container.NewHBox(
		ntr,
		btn,
	)
	ctx.Metadata()[box] = make(map[string]string)
	boxid := fmt.Sprintf("%p", box)[1:]

	lbl := widget.NewLabel("Meep")
	ctx.Metadata()[lbl] = make(map[string]string)
	lblid := fmt.Sprintf("%p", lbl)[1:]

	con := container.NewVBox(
		lbl,
		box,
	)
	ctx.Metadata()[con] = make(map[string]string)
	ctx.Metadata()[con]["name"] = "coco"

	name := "what"
	buf := &bytes.Buffer{}
	assert.NoError(t, ExportGo(con, ctx, name, buf))

	lines := []string{
		btnid + ` := widget.NewButton("Foo", nil)`,
		lblid + ` := widget.NewLabel("Meep")`,
		ntrid + ` := widget.NewEntry()`,
	}
	sort.Strings(lines)

	attrLines := []string{
		ntrid + `.OnSubmitted = g.coco.Hide`,
		btnid + `.OnTapped = ` + ntrid + `.Hide`,
	}
	sort.Strings(attrLines)

	data := struct {
		BtnID, NtrID, LblID, BoxID string
		Lines                      []string
		AttrLines                  []string
	}{
		btnid, ntrid, lblid, boxid,
		lines,
		attrLines,
	}

	exp, err := tools.RenderCode(`// auto-generated
// Code generated by GUI builder.

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

type whatGui struct {
	win fyne.Window

	coco *fyne.Container
}

func newWhatGUI() *whatGui {
	return &whatGui{}
}

func (g *whatGui) makeUI() fyne.CanvasObject {
	{{ range .Lines -}}
	{{.}}
	{{ end -}}
	{{.BoxID}} := container.NewVBox(
		{{.NtrID}},
		{{.BtnID}})
	g.coco = container.NewVBox(
		{{.LblID}},
		{{.BoxID}})
{{ range .AttrLines }}
	{{ . }}
	{{- end }}

	return g.coco
}
`, data)
	assert.NoError(t, err)

	assert.Equal(t, exp, buf.String())
}

func TestStringMapToSlice(t *testing.T) {
	m := map[string]string{
		"bam": "4",
		"bar": "2",
		"foo": "1",
		"zap": "3",
	}
	assert.Equal(t, []string{"4", "2", "1", "3"}, stringMapToSlice(m, func(a, b string) bool {
		return a < b
	}))

	m2 := map[string]string{
		"bam": "a",
		"bar": "b",
		"foo": "c",
		"moo": "d",
		"zap": "e",
	}
	d2 := map[string]int{
		"bam": 4,
		"bar": 2,
		"foo": 1,
		"moo": 1,
		"zap": 3,
	}
	assert.Equal(t, []string{"c", "d", "b", "e", "a"}, stringMapToSlice(m2, func(a, b string) bool {
		if d2[a] == d2[b] {
			return a < b
		}
		return d2[a] < d2[b]
	}))
}
